# Np.eye()

In [ ]:
# create a identical like matrix where the main diagonal is 1 and all other elements are 0

# np.identity

In [1]:
import numpy as np 
arr = np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
