# Numpy(Numerical Python)

In [2]:
import numpy as np
print(np.__version__)

2.5.1


# Numpy Array

In [6]:
import numpy as np

numbers = np.array([1,2,3,4,5])
print(numbers)
print(type(numbers))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# ndarray

In [7]:
# 0 dimensional array
zero_dimensional_array = np.array(42)
print(zero_dimensional_array)

42


In [8]:
# 1 dimensional array
one_dimensional_array = np.array([1,2,3,4,5])
print(one_dimensional_array)

[1 2 3 4 5]


In [10]:
# 2 dimensional array
two_dimensional_array = np.array([[1,2,3],[4,5,6]])
print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 dimensional array
#Collection of matrices
three_dimensional_array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[9,0,8]]])
print(three_dimensional_array)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [9 0 8]]]


# N-dim

In [13]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a.ndim)

1


In [15]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [16]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[2,3,4]]])
print(c.ndim)

3


# Shape

In [17]:
a = np.array([10,20,30,40])
print(a.shape)

(4,)


In [19]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

(2, 3)


In [ ]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(c.shape)

(2, 2, 3)


# Size

In [22]:
b = np.array([[1,2,3],[4,5,6]])
print(b.size)

6


In [23]:
c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(c.size)

12


# Dtypes

In [24]:
a = np.array([10,20,30,40,50])
print(a.dtype)

int64


In [25]:
b = np.array([1.5,2.5,3.6])
print(b.dtype)

float64


# Itemsize

In [28]:
# Memory size of each element 
a= np.array([10,20,30,40,50])
print(a.itemsize)

8


# nbytes

In [ ]:
# total memory used by the array in bytes
a = np.array([10,20,30,40,50])
print(a.nbytes)

40
